"use client";

import { useEffect, useState } from "react";
import api from "@/lib/api";
import { Commission } from "@/lib/types";
import { inr, dateShort } from "@/lib/format";
import { exportCsv } from "@/lib/csv";
import { PageHeader, Card, KpiCard, Table, Th, Td, StatusBadge, Button, Loading, EmptyState, ErrorState } from "@/components/ui";

type Tab = "All" | "Pending" | "Approved" | "Rejected" | "Paid";
const tabs: Tab[] = ["All", "Pending", "Approved", "Rejected", "Paid"];

interface Summary {
  total: number;
  pending: number;
  approved: number;
  rejected: number;
  paid: number;
}

interface CommissionRule {
  tier: "Standard" | "Premium Creator" | "Brand Partner";
  type: "percentage" | "fixed";
  value: number;
  description: string;
}

export default function CommissionsPage() {
  const [tab, setTab] = useState<Tab>("All");
  const [rows, setRows] = useState<Commission[] | null>(null);
  const [summary, setSummary] = useState<Summary | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [rules, setRules] = useState<CommissionRule[] | null>(null);
  const [rulesOpen, setRulesOpen] = useState(false);
  const [rulesDraft, setRulesDraft] = useState<Record<string, number>>({});
  const [savingRules, setSavingRules] = useState(false);

  function load() {
    const path = tab === "All" ? "/commissions" : `/commissions?status=${tab}`;
    api.get<Commission[]>(path).then((r) => setRows(r.reverse())).catch((e) => setError(e.message));
    api.get<Summary>("/commissions/summary").then(setSummary);
  }
  useEffect(load, [tab]);

  function loadRules() {
    api.get<CommissionRule[]>("/commissions/rules").then((r) => {
      setRules(r);
      setRulesDraft(Object.fromEntries(r.map((x) => [x.tier, x.value])));
    });
  }
  useEffect(loadRules, []);

  async function saveRules() {
    if (!rules) return;
    setSavingRules(true);
    try {
      await Promise.all(
        rules
          .filter((r) => rulesDraft[r.tier] !== r.value)
          .map((r) => api.patch(`/commissions/rules/${encodeURIComponent(r.tier)}`, { value: rulesDraft[r.tier] }))
      );
      loadRules();
      setRulesOpen(false);
    } finally {
      setSavingRules(false);
    }
  }

  async function adjust(id: string) {
    const amountStr = window.prompt("Adjustment amount (₹) — positive to add, negative to deduct:");
    if (amountStr === null) return;
    const amount = Number(amountStr);
    if (Number.isNaN(amount) || amount === 0) return;
    const reason = window.prompt("Reason for adjustment?") || "Manual adjustment";
    await api.post(`/commissions/${id}/adjust`, { amount, reason });
    load();
  }

  if (error) return <ErrorState message={error} />;

  return (
    <div>
      <PageHeader
        title="Commission Ledger"
        subtitle="Every commission record generated by the engine, across all affiliates — pending, approved, rejected and paid."
        action={
          <div className="flex gap-2">
            <Button
              variant="secondary"
              onClick={() =>
                exportCsv(
                  "commissions.csv",
                  (rows || []).map((c) => ({
                    affiliate: c.affiliate,
                    tier: c.tier,
                    amount: c.amount,
                    status: c.status,
                    reason: c.rejectedReason || "",
                    calculatedOn: c.calculatedOn,
                    approvedOn: c.approvedOn || "",
                  }))
                )
              }
            >
              Export
            </Button>
            <Button variant="secondary" onClick={() => setRulesOpen((v) => !v)}>
              {rulesOpen ? "Close rules" : "Commission Rules"}
            </Button>
          </div>
        }
      />

      {rulesOpen && (
        <Card className="p-5 mb-6">
          <h2 className="font-display font-semibold text-[15px] mb-1">Commission Rules by Tier</h2>
          <p className="text-xs text-[var(--muted)] mb-4">
            Percentage tiers apply to the revenue of the qualifying conversion; fixed tiers pay a flat amount per
            conversion. Changes apply to commission calculated after saving — existing records are unaffected.
          </p>
          {!rules ? (
            <Loading />
          ) : (
            <div className="grid grid-cols-3 gap-4">
              {rules.map((r) => (
                <div key={r.tier} className="border border-[var(--line)] rounded-lg p-3">
                  <div className="text-sm font-medium mb-1">{r.tier}</div>
                  <div className="text-[11px] text-[var(--muted)] mb-2">{r.description}</div>
                  <div className="flex items-center gap-2">
                    {r.type === "percentage" ? (
                      <>
                        <input
                          type="number"
                          className="input w-20"
                          value={rulesDraft[r.tier] ?? r.value}
                          onChange={(e) => setRulesDraft((d) => ({ ...d, [r.tier]: Number(e.target.value) }))}
                        />
                        <span className="text-sm text-[var(--muted)]">%</span>
                      </>
                    ) : (
                      <>
                        <span className="text-sm text-[var(--muted)]">₹</span>
                        <input
                          type="number"
                          className="input w-24"
                          value={rulesDraft[r.tier] ?? r.value}
                          onChange={(e) => setRulesDraft((d) => ({ ...d, [r.tier]: Number(e.target.value) }))}
                        />
                      </>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
          <div className="mt-4">
            <Button onClick={saveRules} disabled={savingRules}>
              {savingRules ? "Saving…" : "Save rules"}
            </Button>
          </div>
        </Card>
      )}

      {summary && (
        <div className="grid grid-cols-5 gap-4 mb-6">
          <KpiCard label="Total" value={inr(summary.total)} accent="violet" />
          <KpiCard label="Pending" value={inr(summary.pending)} accent="amber" />
          <KpiCard label="Approved" value={inr(summary.approved)} accent="teal" />
          <KpiCard label="Rejected" value={inr(summary.rejected)} accent="coral" />
          <KpiCard label="Paid" value={inr(summary.paid)} accent="teal" />
        </div>
      )}

      <div className="flex gap-1 mb-4">
        {tabs.map((t) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={`px-3 py-1.5 rounded-lg text-[13px] font-medium ${
              tab === t ? "bg-[var(--violet)] text-white" : "bg-white border border-[var(--line)] text-[var(--muted)]"
            }`}
          >
            {t}
          </button>
        ))}
      </div>

      <Card>
        {!rows ? (
          <Loading />
        ) : rows.length === 0 ? (
          <EmptyState title={`No ${tab === "All" ? "" : tab.toLowerCase()} commission records`} />
        ) : (
          <Table>
            <thead>
              <tr>
                <Th>Affiliate</Th>
                <Th>Tier</Th>
                <Th>Amount</Th>
                <Th>Status</Th>
                <Th>Reason</Th>
                <Th>Calculated on</Th>
                <Th>Actions</Th>
              </tr>
            </thead>
            <tbody>
              {rows.map((c) => (
                <tr key={c.id}>
                  <Td>{c.affiliate}</Td>
                  <Td>{c.tier}</Td>
                  <Td className="font-mono">{inr(c.amount)}</Td>
                  <Td>
                    <div className="flex items-center gap-1.5">
                      <StatusBadge status={c.status} />
                      {c.status === "Pending" && !c.eligibleForApproval && (
                        <span className="text-[10px] text-[var(--muted)]">holding period</span>
                      )}
                    </div>
                  </Td>
                  <Td className="text-[12px] text-[var(--muted)] max-w-[220px]">{c.rejectedReason || "—"}</Td>
                  <Td>{dateShort(c.calculatedOn)}</Td>
                  <Td>
                    <div className="flex gap-2 flex-wrap">
                      {c.status === "Pending" && (
                        <>
                          <Button onClick={() => api.post(`/commissions/${c.id}/approve`).then(load)}>Approve</Button>
                          <Button
                            variant="secondary"
                            onClick={() =>
                              api
                                .post(`/commissions/${c.id}/reject`, { reason: window.prompt("Reason?") || "Not specified" })
                                .then(load)
                            }
                          >
                            Reject
                          </Button>
                        </>
                      )}
                      {(c.status === "Pending" || c.status === "Approved") && (
                        <Button variant="secondary" onClick={() => adjust(c.id)}>
                          Adjust
                        </Button>
                      )}
                      {c.status === "Approved" && (
                        <Button
                          variant="secondary"
                          onClick={() =>
                            api
                              .post(`/commissions/${c.id}/reverse`, { reason: window.prompt("Reversal reason?") || "Fraud found" })
                              .then(load)
                          }
                        >
                          Reverse
                        </Button>
                      )}
                    </div>
                  </Td>
                </tr>
              ))}
            </tbody>
          </Table>
        )}
      </Card>
    </div>
  );
}
